2023-03-02 23:35:22 align.main INFO : Reading netlist: /home/kevin/Downloads/msvsd3bitfadc/week3/align-counter/counter/counter.sp subckt=COUNTER, flat=0
2023-03-02 23:35:22 align.compiler.compiler INFO : Starting topology identification...
2023-03-02 23:35:22 align.cmdline ERROR : Fatal Error. Cannot proceed
Traceback (most recent call last):
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/cmdline.py", line 176, in parse_args
    return schematic2layout(**vars(arguments))
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/main.py", line 164, in schematic2layout
    primitive_lib = generate_hierarchy(netlist, subckt, topology_dir, flatten, pdk_dir)
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/compiler/compiler.py", line 27, in generate_hierarchy
    ckt_data, primitive_library = compiler_input(
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/compiler/compiler.py", line 76, in compiler_input
    ckt_parser.parse(lines)
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/schema/parser.py", line 88, in parse
    self._dispatch(cache)
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/schema/parser.py", line 106, in _dispatch
    self._process_instance(token.value.upper(), args, kwargs)
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/schema/parser.py", line 150, in _process_instance
    if self.library.find(model):
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/schema/library.py", line 22, in find
    return next((x for x in self if x.name == name.upper()), None)
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/schema/library.py", line 22, in <genexpr>
    return next((x for x in self if x.name == name.upper()), None)
AttributeError: 'float' object has no attribute 'upper'
